In [74]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import preprocessing
import re
import nltk
from sklearn.metrics import  precision_recall_fscore_support
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

In [75]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/230.1 MB 15.2 kB/s eta 4:11:02
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/behrad/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
    yield
  File "/Users/behrad/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/behrad/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/Users/behrad/opt/anaconda3/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/Users/behrad/opt/anaconda3/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/Users/behrad/opt/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/behrad/opt/anaconda3/lib/python3.9/ssl.py",

In [41]:
data=pd.read_csv("/Users/behrad/Downloads/amazon.tsv",on_bad_lines='skip',delimiter='\t')
df= pd.DataFrame(data)
df

marketplace  customer_id       review_id  product_id  product_parent  \
0               US      3653882  R3O9SGZBVQBV76  B00FALQ1ZC       937001370   
1               US     14661224   RKH8BNC3L5DLF  B00D3RGO20       484010722   
2               US     27324930  R2HLE8WKZSU3NL  B00DKYC7TK       361166390   
3               US      7211452  R31U3UH5AZ42LL  B000EQS1JW       958035625   
4               US     12733322  R2SV659OUJ945Y  B00A6GFD7S       765328221   
...            ...          ...             ...         ...             ...   
960199          US     39508379   REH8UQZAXQS40  B00005OT9I         2153632   
960200          US     44704251   RJ14QPZEOI9P8  B00005QEM6       903687397   
960201          US     40571775  R2B1G5650WWFCE  B00005QEME       252821780   
960202          US     44474855  R2MMGPUWXXOFI2  B00004YK0H       118389241   
960203          US     44474855  R2BZMVAERMRUDE  B00004YK0H       118389241   

                                            product_title product_category  \
0       Invicta Women's 15150 "Angel" 18k Yellow Gold ...          Watches   
1       Kenneth Cole New York Women's KC4944 Automatic...          Watches   
2       Ritche 22mm Black Stainless Steel Bracelet Wat...          Watches   
3       Citizen Men's BM8180-03E Eco-Drive Stainless S...          Watches   
4       Orient ER27009B Men's Symphony Automatic Stain...          Watches   
...                                                   ...              ...   
960199         Xhilaration&#174; Silver Dial Bangle Watch          Watches   
960200  Armitron Men's Titanium 3 Eye Sport Analog Chr...          Watches   
960201         Men's Timex Internet Messenger Sport Watch          Watches   
960202                  Energizer 393 Button Cell Battery          Watches   
960203                  Energizer 393 Button Cell Battery          Watches   

        star_rating  helpful_votes  total_votes vine verified_purchase  \
0                 5              0            0    N                 Y   
1                 5              0            0    N                 Y   
2                 2              1            1    N                 Y   
3                 5              0            0    N                 Y   
4                 4              0            0    N                 Y   
...             ...            ...          ...  ...               ...   
960199            2             17           17    N                 N   
960200            5              9           10    N                 N   
960201            5              3           16    N                 N   
960202            4              0            0    N                 N   
960203            4              5            7    N                 N   

                                   review_headline  \
0                                       Five Stars   
1       I love thiswatch it keeps time wonderfully   
2                                        Two Stars   
3                                       Five Stars   
4         Beautiful face, but cheap sounding links   
...                                            ...   
960199                    Great prize - but size??   
960200                        A very classy watch!   
960201                       This is a great watch   
960202                     Now watt a minute here.   
960203       1/10 Watt difference for hearing aids   

                                              review_body review_date  
0       Absolutely love this watch! Get compliments al...  2015-08-31  
1            I love this watch it keeps time wonderfully.  2015-08-31  
2                                               Scratches  2015-08-31  
3       It works well on me. However, I found cheaper ...  2015-08-31  
4       Beautiful watch face.  The band looks nice all...  2015-08-31  
...                                                   ...         ...  
960199  It's a great watch - but you don't have a chan...  2001-12-13  
960200 

In [42]:
df=df.dropna()

In [43]:
x=df['review_body']
y=df['star_rating']


In [44]:
y = y.apply(lambda x: 0 if x <= 2 else 2 if x == 3 else 1)

In [45]:


# Download stopwords if not already downloaded
nltk.download('stopwords')
nltk.download('punkt')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word.casefold() not in stop_words]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text



df = pd.DataFrame(data)

x = x.astype(str)

# Apply stopword removal to a specific column
x = x.apply(remove_stopwords)

# Print the processed dataset
print(x)


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/behrad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/behrad/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


0         Absolutely love watch ! Get compliments almost...
1                       love watch keeps time wonderfully .
2                                                 Scratches
3         works well . However , found cheaper prices pl...
4         Beautiful watch face . band looks nice around ...
                                ...                        
960199    's great watch - n't chance change size cant f...
960200    Well worth price . light weight , classy looki...
960201    Dear Targeteers , < BR > watch exelent . every...
960202    old days , common hearing battery past used ta...
960203    found # 393 watch battery size # 13 hearing ba...
Name: review_body, Length: 960043, dtype: object


In [47]:
def remove_punctuation(text):
    pattern = r'[^\w\s]'
    filtered_text = re.sub(pattern, '', text)
    return filtered_text


#filtered_text = remove_punctuation(text)

x = x.apply(remove_punctuation)
print(x)

0         Absolutely love watch  Get compliments almost ...
1                        love watch keeps time wonderfully 
2                                                 Scratches
3         works well  However  found cheaper prices plac...
4         Beautiful watch face  band looks nice around  ...
                                ...                        
960199       s great watch  nt chance change size cant fit 
960200    Well worth price  light weight  classy looking...
960201    Dear Targeteers   BR  watch exelent  everythin...
960202    old days  common hearing battery past used tak...
960203    found  393 watch battery size  13 hearing batt...
Name: review_body, Length: 960043, dtype: object


In [57]:
x_train, x_test_val, y_train, y_test_val = train_test_split(x, y, test_size=0.4)
x_test, x_val, y_test, y_val = train_test_split(x_test_val, y_test_val, test_size=0.5)




In [58]:
# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Compute TF-IDF features
tfidf_matrix = vectorizer.fit_transform(x_train)

tfidf_matrix1 = vectorizer.fit_transform(x_train)



In [59]:
lr=LogisticRegression()
history=lr.fit(tfidf_matrix,y_train)

x_val  = vectorizer.transform(x_val)
y_pred = lr.predict(x_val)

/Users/behrad/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [66]:
precision, recall, fscore, support = precision_recall_fscore_support(y_val, y_pred)
print(precision)
print(recall)
print(fscore)
accuracy = accuracy_score(y_val, y_pred)
print("Accuracy Score:", accuracy)

[0.73861702 0.90077635 0.43968293]
[0.74009146 0.97177897 0.11227782]
[0.73935351 0.93493154 0.17887736]
Accuracy Score: 0.8677666151065836


In [68]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras import layers

# Example dataset
data = {'text': [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
], 'label': ['A', 'B', 'C', 'A']}

df = pd.DataFrame(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['text'])

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, df['label'], test_size=0.2, random_state=42)

# Convert labels to numeric values
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# Define the neural network architecture
model = tf.keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(tfidf_matrix.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train.toarray(), y_train, epochs=10, batch_size=32, verbose=1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test.toarray(), y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)


ModuleNotFoundError: No module named 'tensorflow'